# Generated by Django 6.0.3 on 2026-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text="Código corto interno, ej. 'LURIN'.", max_length=20, unique=True)),
                ('nombre', models.CharField(help_text="Nombre visible para proveedores y staff, ej. 'Planta Lurín'.", max_length=100)),
                ('sap_whs_code', models.CharField(blank=True, help_text='Código de almacén (WhsCode) en SAP. Sin sincronización real todavía.', max_length=20, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Solo las sedes activas se ofrecen al agendar.')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
    ]
