# Generated by Django 6.0.3 on 2026-08-22 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_seed_sedes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(blank=True, default='', max_length=50)),
                ('razon_social', models.CharField(blank=True, default='', max_length=255)),
                ('correo_electronico', models.CharField(blank=True, default='', max_length=255)),
                ('sap_card_code', models.CharField(help_text='CardCode de SAP (mismo valor que PurchaseOrder.card_code).', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15)),
                ('user', models.OneToOneField(blank=True, help_text='Cuenta de Portal vinculada. Nulo hasta que exista un flujo de activación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Proveedor',
                'verbose_name_plural': 'Perfiles de Proveedor',
                'ordering': ['razon_social'],
            },
        ),
    ]
