# Generated by Django 6.0.3 on 2026-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_backfill_supplierprofile_desde_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='True solo mientras el proveedor sigue con la contraseña temporal (su LicTradNum) asignada al darlo de alta desde SAP (Etapa 2). Default False para no afectar cuentas creadas antes de este flujo (manuales, o vinculadas por resolver_perfil_de_usuario) — nunca deben quedar bloqueadas por un flag que no les corresponde.'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='razon_social_legal',
            field=models.CharField(blank=True, default='', help_text='CardFName de SAP — razón social legal/fiscal completa, distinta de razon_social (CardName, nombre comercial corto).', max_length=255),
        ),
    ]
