# Generated by Django 6.0.3 on 2026-08-21 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_seed_sedes'),
        ('operations', '0009_backfill_entrada_mercaderia'),
        ('sap_sync', '0002_purchaseorderline_activa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION_COMPRAS', 'En Revisión (Compras)'), ('OBSERVADA', 'Observada'), ('APROBADA_COMPRAS', 'Aprobada (Compras)'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=25)),
                ('estado_sap', models.CharField(blank=True, choices=[('', 'Sin generar'), ('L', 'Pendiente de confirmar en SAP'), ('B', 'Borrador confirmado en SAP'), ('Y', 'Definitivo confirmado en SAP'), ('C', 'Cancelado en SAP')], default='', max_length=1)),
                ('doc_entry_preliminar', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_entry_definitivo', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_cur', models.CharField(blank=True, help_text='DocCur de SAP (moneda del documento).', max_length=50, null=True)),
                ('tax_date', models.DateField(blank=True, null=True)),
                ('doc_due_date', models.DateField(blank=True, null=True)),
                ('num_at_card', models.CharField(blank=True, help_text='NumAtCard de SAP (número de documento del proveedor).', max_length=100, null=True)),
                ('serie_comprobante', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_operacion', models.CharField(choices=[('02', 'Compra Nacional')], default='02', help_text='U_MSSL_TOP (UDF SAP): Tipo de Operación.', max_length=2)),
                ('clasificacion_bienes_servicios', models.IntegerField(blank=True, choices=[(1, 'Mercadería'), (2, 'Activo'), (3, 'Otros activos'), (4, 'Gastos de educación'), (5, 'Otros gastos')], help_text='U_MSSL_CBS (UDF SAP): Clasificación de Bienes/Servicios Adquiridos.', null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='facturas/xml/%Y/%m/%d/')),
                ('hash_xml', models.CharField(blank=True, default='', max_length=128)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='facturas/pdf/%Y/%m/%d/')),
                ('hash_pdf', models.CharField(blank=True, default='', max_length=128)),
                ('cdr_xml_file', models.FileField(blank=True, null=True, upload_to='facturas/cdr/%Y/%m/%d/')),
                ('hash_cdr', models.CharField(blank=True, default='', max_length=128)),
                ('estado_cdr', models.CharField(blank=True, choices=[('ACEPTADO', 'Aceptado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], help_text='Resultado de services_validacion.extraer_estado_cdr (Sub-fase 3.2).', max_length=10, null=True)),
                ('firma_valida', models.BooleanField(blank=True, help_text='Resultado de services_validacion.validar_firma_xml (Sub-fase 3.2).', null=True)),
                ('entrada_mercaderia', models.ForeignKey(blank=True, help_text='Respaldo del 3-way match (OC / Entrada de Mercancía / Factura).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='operations.entradamercaderia')),
                ('proveedor', models.ForeignKey(help_text='Usuario proveedor (grupo PROVEEDORES) dueño de esta factura.', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='base.sede')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacturaObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ronda', models.PositiveIntegerField(default=1, help_text='Número de ronda de observación/corrección de esta Factura.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_factura', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='invoicing.factura')),
            ],
            options={
                'verbose_name': 'Observación de Factura',
                'verbose_name_plural': 'Observaciones de Factura',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_oc', models.DecimalField(decimal_places=4, editable=False, help_text='Snapshot de la cantidad de OC al crear esta línea. No se actualiza después.', max_digits=18)),
                ('precio_oc', models.DecimalField(decimal_places=4, editable=False, help_text='Snapshot del precio de OC al crear esta línea. No se actualiza después.', max_digits=18)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=18)),
                ('difiere_de_oc', models.BooleanField(default=False, editable=False, help_text='Calculado en save(): True si cantidad o precio difieren del snapshot de OC.')),
                ('aplica_retencion', models.BooleanField(default=False)),
                ('documento_retencion', models.FileField(blank=True, null=True, upload_to='facturas/retenciones/%Y/%m/%d/')),
                ('aplica_detraccion', models.BooleanField(default=False)),
                ('documento_detraccion', models.FileField(blank=True, null=True, upload_to='facturas/detracciones/%Y/%m/%d/')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='invoicing.factura')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_lineas', to='sap_sync.purchaseorderline')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
                'unique_together': {('factura', 'po_line')},
            },
        ),
        migrations.CreateModel(
            name='FacturaOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='invoicing.factura')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_oc', to='sap_sync.purchaseorder')),
            ],
            options={
                'verbose_name': 'OC de Factura',
                'verbose_name_plural': 'OCs de Factura',
                'unique_together': {('factura', 'purchase_order')},
            },
        ),
    ]
