# Generated by Django 6.0.3 on 2026-08-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_backfill_supplierprofile_desde_proveedores'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(help_text='Perfil de proveedor dueño de esta factura.', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='base.supplierprofile'),
        ),
    ]
