# Generated by Django 6.0.3 on 2026-08-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_factura_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturalinea',
            name='hash_documento_detraccion',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='facturalinea',
            name='hash_documento_retencion',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cdr_xml_file',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='factura',
            name='pdf_file',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='factura',
            name='xml_file',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='facturalinea',
            name='documento_detraccion',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='facturalinea',
            name='documento_retencion',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
