# Generated by Django 6.0.3 on 2026-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_facturalinea_hash_documento_detraccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='importe_no_coincide',
            field=models.BooleanField(default=False, help_text='True si importe_total_xml no coincide con la suma de FacturaLinea.cantidad*precio ya cargadas (con tolerancia de centavos). Bloquea el envío a revisión.'),
        ),
        migrations.AddField(
            model_name='factura',
            name='importe_total_xml',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='cac:LegalMonetaryTotal/cbc:PayableAmount extraído del XML. Referencia.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='mensaje_validacion_documentos',
            field=models.TextField(blank=True, default='', help_text='Resumen legible de por qué firma_valida/estado_cdr/importe_no_coincide quedaron como quedaron — para que la razón del bloqueo (o de que todo esté OK) no quede oculta en 3 campos sueltos.'),
        ),
        migrations.AddField(
            model_name='factura',
            name='moneda_xml',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_cdr',
            field=models.CharField(blank=True, choices=[('ACEPTADO', 'Aceptado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], help_text='Resultado de services_validacion.extraer_estado_cdr (Sub-fase 3.3).', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='firma_valida',
            field=models.BooleanField(blank=True, help_text='Resultado de services_validacion.validar_firma_xml (Sub-fase 3.3).', null=True),
        ),
    ]
