# Generated by Django 6.0.3 on 2026-08-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_factura_importe_no_coincide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='error_mensaje_sap',
            field=models.TextField(blank=True, default='', help_text='Mensaje de error reportado por el daemon si SAP rechaza la creación del Preliminar (diagnóstico) — distinto de mensaje_validacion_documentos, que es sobre la validez del propio comprobante (firma/CDR/importe), no sobre SAP.'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_cancelado_sap',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_definitivo_confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_preliminar_confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
