# Generated by Django 6.0.3 on 2026-08-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_factura_error_mensaje_sap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturalinea',
            name='tax_code',
            field=models.CharField(choices=[('IGV', 'IGV (gravado)'), ('IGV_EXE', 'IGV Exonerado')], default='IGV', editable=False, help_text='Snapshot de PurchaseOrderLine.tax_code al crear esta línea — base para el cálculo de IGV en procesar_validacion_documentos (apps/invoicing/services.py).', max_length=10),
        ),
        migrations.AlterField(
            model_name='facturalinea',
            name='difiere_de_oc',
            field=models.BooleanField(default=False, editable=False, help_text='Calculado en save(): True si cantidad difiere de cantidad_oc. Desde la sesión 92 ya NO considera precio (precio/precio_oc son siempre iguales por construcción, ver docstring de la clase).'),
        ),
        migrations.AlterField(
            model_name='facturalinea',
            name='precio',
            field=models.DecimalField(decimal_places=4, help_text='Heredado de PurchaseOrderLine.precio_unitario al crear la línea — no editable por el proveedor desde la sesión 92 (ver docstring de la clase).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='facturalinea',
            name='precio_oc',
            field=models.DecimalField(decimal_places=4, editable=False, help_text='Snapshot del precio de OC (PurchaseOrderLine.precio_unitario) al crear esta línea. No se actualiza después. Desde la sesión 92, siempre igual a `precio` (ver docstring de la clase).', max_digits=18),
        ),
    ]
