# Generated by Django 6.0.3 on 2026-08-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_facturalinea_tax_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='moneda_no_coincide',
            field=models.BooleanField(default=False, help_text='True si moneda_xml no coincide con doc_cur (moneda real de la OC). Bloquea el envío a revisión. No implica ninguna conversión — solo detección.'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='mensaje_validacion_documentos',
            field=models.TextField(blank=True, default='', help_text='Resumen legible de por qué firma_valida/estado_cdr/importe_no_coincide/moneda_no_coincide quedaron como quedaron — para que la razón del bloqueo (o de que todo esté OK) no quede oculta en 4 campos sueltos.'),
        ),
    ]
