# Generated by Django 6.0.3 on 2026-09-02 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_factura_moneda_no_coincide_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_id', models.IntegerField(db_index=True, help_text='PK que tenía la Factura al momento del evento — NO es una FK (la Factura puede ya no existir).')),
                ('tipo', models.CharField(choices=[('ELIMINACION', 'Borrador eliminado por el proveedor')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(default=dict, help_text='Foto de la Factura al momento del evento: numero_documento, proveedor (razon_social/ruc), OC(s) vinculadas, importe total, estado y estado_sap. Suficiente para saber qué se borró sin depender de que la Factura siga existiendo.')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_factura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Factura',
                'verbose_name_plural': 'Eventos de Factura',
                'ordering': ['-fecha'],
            },
        ),
    ]
