# Generated by Django 6.0.3 on 2026-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklyslotrule',
            name='unique_regla_por_plantilla_dia_hora',
        ),
        migrations.AlterField(
            model_name='weeklyslotrule',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], help_text='Día de la semana (0=Lunes, 5=Sábado). Alineado con Python isoweekday()-1.'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyslotrule',
            unique_together={('template', 'dia_semana', 'hora')},
        ),
    ]
