# Generated by Django 6.0.3 on 2026-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_scheduletemplate_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplate',
            name='nombre',
            field=models.CharField(help_text="Nombre descriptivo de la plantilla, ej: 'Semana Estándar'. No hace falta indicar la sede aquí — cada plantilla ya pertenece a una Sede concreta vía el campo 'sede'.", max_length=100),
        ),
    ]
