# Generated by Django 6.0.3 on 2026-04-14 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('sap_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PLANTA', 'En Planta'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('codigo_qr', models.CharField(blank=True, help_text='Código QR único. Igual que Appointment.token_qr.', max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_total_planta', models.DurationField(blank=True, null=True)),
                ('tipo_flujo', models.CharField(choices=[('CON_CALIDAD', 'Con Calidad (Materia Prima)'), ('SOLO_ALMACEN', 'Solo Almacén (Comercial)')], default='CON_CALIDAD', help_text='Determina si el ticket pasa por Calidad (CON_CALIDAD) o va directo a Almacén (SOLO_ALMACEN). Se calcula al confirmar la cita según las OCs vinculadas.', max_length=20)),
                ('appointment', models.OneToOneField(help_text='Vinculación directa con la cita agendada', on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='appointments.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('VIGILANCIA_ENTRADA', 'Vigilancia - Ingreso'), ('ALMACEN_RECEPCION', 'Almacén - Recepción'), ('CALIDAD_INSPECCION', 'Calidad - Inspección'), ('VIGILANCIA_SALIDA', 'Vigilancia - Salida')], max_length=30)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='operations.ticket')),
                ('usuario', models.ForeignKey(help_text='Responsable que ejecutó/cerró la etapa', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketLineInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('VIGILANCIA', 'Vigilancia'), ('ALMACEN', 'Almacén'), ('CALIDAD', 'Calidad')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CONFORME', 'Conforme'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('cantidad_sap', models.DecimalField(decimal_places=4, editable=False, max_digits=18)),
                ('cantidad_modificada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('requiere_coa', models.BooleanField(default=False, help_text='Copia del flag requiere_coa de la línea de OC al momento de crear la inspección.')),
                ('coa_url', models.URLField(blank=True, help_text='Link de acceso al COA en OneDrive M365. Se guarda tras la carga del proveedor.', max_length=500, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evidencia_url', models.FileField(blank=True, null=True, upload_to='evidencias/inspeccion/%Y/%m/%d/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sap_sync.purchaseorderline')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='operations.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ticket', 'po_line', 'etapa')},
            },
        ),
    ]
