# Generated by Django 6.0.3 on 2026-04-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlineinspection',
            name='doc_num',
            field=models.IntegerField(default=0, help_text='Número de la Orden de Compra de SAP (ej. 16089783).'),
            preserve_default=False,
        ),
    ]
