# Generated by Django 6.0.3 on 2026-07-30 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_ticketlineinspection_doc_num'),
        ('sap_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLineCOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_url', models.URLField(help_text='Link de acceso al COA en OneDrive M365.', max_length=500)),
                ('evidencia_url', models.FileField(blank=True, help_text='Archivo local del COA, si aplica (independiente del link de OneDrive).', null=True, upload_to='documentos/coa_lineas/%Y/%m/%d/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sap_sync.purchaseorderline')),
                ('subido_por', models.ForeignKey(help_text='Usuario que cargó el COA (normalmente el proveedor).', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coas', to='operations.ticket')),
            ],
            options={
                'verbose_name': 'COA de Línea',
                'verbose_name_plural': 'COAs de Línea',
                'unique_together': {('ticket', 'po_line')},
            },
        ),
    ]
