# Generated by Django 6.0.3 on 2026-07-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_ticketlinecoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='etapa_actual',
            field=models.CharField(choices=[('PENDIENTE_INGRESO', 'Pendiente de Ingreso (Vigilancia)'), ('VIGILANCIA_INGRESO', 'Ingreso Registrado (Vigilancia)'), ('ALMACEN', 'Recepción en Almacén'), ('CALIDAD', 'Inspección de Calidad'), ('VIGILANCIA_SALIDA', 'Salida Registrada (Vigilancia)'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE_INGRESO', help_text='Última etapa operativa completada. OperationsService la valida antes de cada acción y la avanza al terminarla (candado de servicio).', max_length=20),
        ),
    ]
