# Generated by Django 6.0.3 on 2026-07-30 20:29
#
# Inicializa Ticket.etapa_actual para los tickets ya existentes, según su
# estado y las TicketStage que ya tenga registradas. No deja el campo con
# el valor por defecto (PENDIENTE_INGRESO) en tickets que ya avanzaron.

from django.db import migrations


def inicializar_etapa_actual(apps, schema_editor):
    Ticket = apps.get_model('operations', 'Ticket')
    TicketStage = apps.get_model('operations', 'TicketStage')

    for ticket in Ticket.objects.all():
        if ticket.estado == 'PROGRAMADO':
            etapa = 'PENDIENTE_INGRESO'

        elif ticket.estado in ('FINALIZADO', 'CANCELADO'):
            etapa = 'FINALIZADO'

        else:  # EN_PLANTA — reconstruimos la posición según las TicketStage existentes
            etapas_registradas = set(
                TicketStage.objects.filter(ticket=ticket).values_list('etapa', flat=True)
            )

            if 'VIGILANCIA_SALIDA' in etapas_registradas:
                etapa = 'VIGILANCIA_SALIDA'
            elif 'CALIDAD_INSPECCION' in etapas_registradas:
                etapa = 'CALIDAD'
            elif 'ALMACEN_FINALIZADO' in etapas_registradas:
                # Cierre de flujo SOLO_ALMACEN (registrar_calidad salta CALIDAD)
                etapa = 'VIGILANCIA_SALIDA'
            elif 'ALMACEN_RECEPCION' in etapas_registradas:
                etapa = 'ALMACEN'
            elif 'VIGILANCIA_ENTRADA' in etapas_registradas:
                etapa = 'VIGILANCIA_INGRESO'
            else:
                # EN_PLANTA sin ninguna TicketStage: no debería ocurrir en el flujo
                # normal, pero no dejamos el campo inconsistente.
                etapa = 'PENDIENTE_INGRESO'

        ticket.etapa_actual = etapa
        ticket.save(update_fields=['etapa_actual'])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_ticket_etapa_actual'),
    ]

    operations = [
        migrations.RunPython(inicializar_etapa_actual, reverse_code=migrations.RunPython.noop),
    ]
