# Generated by Django 6.0.3 on 2026-08-02 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_inicializar_etapa_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDatosIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=15)),
                ('conductor_dni', models.CharField(blank=True, help_text='DNI o Carné de Extranjería del conductor.', max_length=20, verbose_name='DNI/CE del conductor')),
                ('conductor_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre y apellidos del conductor')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(help_text='Usuario que registró/corrigió estos datos (normalmente el proveedor).', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_ingreso', to='operations.ticket')),
            ],
            options={
                'verbose_name': 'Datos de Ingreso',
                'verbose_name_plural': 'Datos de Ingreso',
            },
        ),
    ]
