# Generated by Django 6.0.3 on 2026-08-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_ticketdatosingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='muelle',
            field=models.CharField(blank=True, default='', help_text="Muelle/puerta de descarga real, capturado al 'Iniciar Recepción' por Almacén o Materia Prima. Campo propio del Ticket — no reutiliza AppointmentSlot.dock (ese es el muelle asignado por Programación/Compras al horario; este es el muelle real usado en la recepción de este Ticket específico).", max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requiere_calidad',
            field=models.BooleanField(default=False, help_text="Decide si el ticket pasa a CALIDAD tras la recepción. Reemplaza a tipo_flujo como señal operativa: se captura explícitamente al 'Iniciar Recepción' (Almacén o Materia Prima), no se infiere automáticamente de las OCs vinculadas."),
        ),
    ]
