# Generated by Django 6.0.3 on 2026-08-19 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_ticket_muelle_ticket_requiere_calidad'),
        ('sap_sync', '0002_purchaseorderline_activa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sap', models.CharField(blank=True, choices=[('', 'Sin generar'), ('L', 'Pendiente de confirmar en SAP'), ('B', 'Borrador confirmado en SAP'), ('Y', 'Definitivo confirmado en SAP')], default='', max_length=1)),
                ('doc_entry_borrador', models.IntegerField(blank=True, help_text="DocEntry del borrador en SAP, asignado por el daemon al confirmar (estado_sap='B').", null=True)),
                ('doc_entry_definitivo', models.IntegerField(blank=True, help_text="DocEntry del documento definitivo en SAP, asignado por el daemon (estado_sap='Y').", null=True)),
                ('error_mensaje', models.TextField(blank=True, default='', help_text='Mensaje de error reportado por el daemon si SAP rechaza la entrada (diagnóstico).')),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_borrador_confirmado', models.DateTimeField(blank=True, null=True)),
                ('fecha_definitivo_confirmado', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_mercaderia', to='operations.ticket')),
            ],
            options={
                'verbose_name': 'Entrada de Mercadería',
                'verbose_name_plural': 'Entradas de Mercadería',
            },
        ),
        migrations.CreateModel(
            name='EntradaMercaderiaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='operations.entradamercaderia')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sap_sync.purchaseorderline')),
            ],
            options={
                'verbose_name': 'Línea de Entrada de Mercadería',
                'verbose_name_plural': 'Líneas de Entrada de Mercadería',
                'unique_together': {('entrada', 'po_line')},
            },
        ),
    ]
