# Generated by Django 6.0.3 on 2026-09-01 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_entrada_estado_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercaderiaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REABIERTA', 'Reabierta para corrección')], max_length=20)),
                ('mensaje', models.TextField(blank=True, default='', help_text='Contexto del evento (ej. el error de SAP que se estaba corrigiendo).')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operations.entradamercaderia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Entrada de Mercadería',
                'verbose_name_plural': 'Eventos de Entrada de Mercadería',
                'ordering': ['-fecha'],
            },
        ),
    ]
