# Generated by Django 6.0.3 on 2026-04-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_entry', models.IntegerField(help_text='ID interno SAP', unique=True)),
                ('doc_num', models.IntegerField(help_text='Número de documento SAP', unique=True)),
                ('card_code', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=255)),
                ('e_mail', models.CharField(max_length=255)),
                ('status', models.CharField(default='O', max_length=20)),
                ('u_mss_tdb', models.CharField(blank=True, default='', help_text="UDF SAP: 'MP' para Materia Prima, vacío/otro para Comercial.", max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField()),
                ('item_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity_sap', models.DecimalField(decimal_places=4, max_digits=18)),
                ('und_medida', models.CharField(max_length=50)),
                ('requiere_coa', models.BooleanField(default=False, help_text='True → esta línea necesita inspección de Calidad y COA. Se pre-marca automáticamente para OCs MP; ajustable por Compras.')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sap_sync.purchaseorder')),
            ],
        ),
    ]
