# Generated by Django 6.0.3 on 2026-08-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line_num',
            field=models.IntegerField(help_text='LineNum de SAP: identificador estable de la línea dentro de la OC, usado como clave de upsert en cada sincronización.'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderline',
            unique_together={('purchase_order', 'line_num')},
        ),
    ]
