# Generated by Django 6.0.3 on 2026-08-28 18:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0002_purchaseorderline_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='precio_total_linea',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='LineTotal de SAP: total NETO de la línea (cantidad × precio unitario, después de descuento de línea si aplica) — SIN IGV incluido. No confundir con un total final para el proveedor, que sí incluiría el impuesto.', max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='PriceBefDi de SAP: precio unitario, antes de descuento.', max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_code',
            field=models.CharField(choices=[('IGV', 'IGV (gravado)'), ('IGV_EXE', 'IGV Exonerado')], default='IGV', help_text='TaxCode de SAP: código de impuesto aplicado a la línea.', max_length=10),
        ),
    ]
