# Generated by Django 6.0.3 on 2026-08-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0003_purchaseorderline_precio_total_linea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='doc_cur',
            field=models.CharField(blank=True, default='', help_text="DocCur de SAP: moneda del documento (texto directo, ej. 'USD'/'SOL').", max_length=5),
        ),
    ]
