# Generated by Django 6.0.3 on 2026-04-14 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sap_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('dock', models.CharField(help_text='Muelle/Puerto', max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('is_full_override', models.BooleanField(default=False, help_text='Si True, el slot no acepta nuevas citas aunque no haya llegado a la capacidad máxima. Se activa manualmente desde el panel de admin o automáticamente al confirmar una cita que llena el slot.')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coa_pdf', models.FileField(blank=True, help_text='Certificado de Análisis. Obligatorio para autorizar el ingreso a planta.', null=True, upload_to='documentos/coa/%Y/%m/')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADO', 'Rechazado'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada (En Planta)')], default='SOLICITADO', max_length=20)),
                ('token_qr', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('lugar_entrega', models.CharField(choices=[('LURIN', 'Planta Lurin'), ('PUNTA_NEGRA', 'Almacén Punta Negra'), ('DISTRIBUCION', 'Distribucion')], default='LURIN', max_length=20)),
                ('observaciones_admin', models.TextField(blank=True, null=True)),
                ('fecha_respuesta_admin', models.DateTimeField(blank=True, help_text='Timestamp de cuando Almacén confirmó o rechazó la cita.', null=True)),
                ('purchase_orders', models.ManyToManyField(to='sap_sync.purchaseorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_citas', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.appointmentslot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
