# Generated by Django 6.0.3 on 2026-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='coa_configurado',
            field=models.BooleanField(default=False, help_text='True desde que Compras guarda una configuración de COA por línea para esta cita (ajax_configurar_items_coa), aunque sea sin cambios. Mientras esté en False, AppointmentService.preparar_detalle_compras puede sugerir requiere_coa=True por defecto en las líneas de OC Materia Prima al abrir la configuración; una vez en True, ya no vuelve a tocarlas, para no sobreescribir una decisión manual ya guardada.'),
        ),
    ]
