# Generated by Django 6.0.3 on 2026-08-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_backfill_coa_configurado'),
        ('base', '0002_seed_sedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sede',
            field=models.ForeignKey(help_text='Sede de entrega elegida por el proveedor al solicitar la cita.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='base.sede'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='sede',
            field=models.ForeignKey(help_text='Sede a la que pertenece este cupo horario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='base.sede'),
        ),
    ]
