# Generated by Django 6.0.3 on 2026-08-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_backfill_sede'),
        ('base', '0002_seed_sedes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lugar_entrega',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sede',
            field=models.ForeignKey(help_text='Sede de entrega elegida por el proveedor al solicitar la cita.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='base.sede'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='sede',
            field=models.ForeignKey(help_text='Sede a la que pertenece este cupo horario.', on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='base.sede'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('sede', 'date', 'start_time')},
        ),
    ]
