# Generated by Django 6.0.3 on 2026-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointmentslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('SEDE_ERRONEA', 'Sede errónea'), ('COA_INCOMPLETO', 'COA incompleto'), ('DATOS_INCORRECTOS', 'Datos incorrectos'), ('OTRO', 'Otro')], default='', help_text='Motivo estructurado del rechazo — obligatorio al rechazar una cita (status=RECHAZADO, ver ajax_rechazar_cita_compras/ajax_rechazar_cita), vacío en cualquier otro estado. Campo separado de observaciones_admin a propósito: este es una elección de una lista cerrada (para mostrarle al proveedor qué corregir), mientras que observaciones_admin sigue siendo texto libre opcional, usado también para notas al confirmar.', max_length=20),
        ),
    ]
